# Generated by Django 5.0.3 on 2024-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseDados",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "entrada",
                    models.DateField(blank=True, db_column="ENTRADA", null=True),
                ),
                ("saida", models.DateField(blank=True, db_column="SAÍDA", null=True)),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="NOME", max_length=100, null=True
                    ),
                ),
                (
                    "diarias",
                    models.IntegerField(
                        blank=True, db_column="DIARIAS", default=0, null=True
                    ),
                ),
                (
                    "graduacao",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("GEN", "GEN"),
                            ("CEL", "CEL"),
                            ("TC", "TC"),
                            ("MAJ", "MAJ"),
                            ("CAP", "CAP"),
                            ("1º TEN", "1º TEN"),
                            ("2º TEN", "2º TEN"),
                            ("ASP", "ASP"),
                            ("SO", "SO"),
                            ("ST", "ST"),
                            ("1º SGT", "1º SGT"),
                            ("2º SGT", "2º SGT"),
                            ("3º SGT", "3º SGT"),
                            ("CIVIL", "CIVIL"),
                        ],
                        db_column="GRADUAÇÃO",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, db_column="TELEFONE", max_length=15, null=True
                    ),
                ),
                (
                    "qtde_quartos",
                    models.IntegerField(
                        blank=True, db_column="QTDE_QUARTOS", null=True
                    ),
                ),
                (
                    "qtde_hosp",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                        ],
                        db_column="QTDE_HOSP",
                        null=True,
                    ),
                ),
                (
                    "especial",
                    models.TextField(
                        blank=True,
                        choices=[("Sim", "Sim"), ("Não", "Não")],
                        db_column="ESPECIAL",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="EMAIL", max_length=100, null=True
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_column="CPF", max_length=15, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CIVIL", "CIVIL"),
                            ("MILITAR DA ATIVA", "MILITAR DA ATIVA"),
                            ("MILITAR DA RESERVA", "MILITAR DA RESERVA"),
                            ("PENSIONISTA", "PENSIONISTA"),
                            ("DEP. DESACOMPANHADO", "DEP. DESACOMPANHADO"),
                        ],
                        db_column="STATUS",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Casal", "Casal"),
                            ("Solteiro", "Solteiro"),
                            ("Outro", "Outro"),
                        ],
                        db_column="TIPO",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "sexo",
                    models.TextField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        db_column="SEXO",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, db_column="CIDADE", max_length=100, null=True
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "AL"),
                            ("AM", "AM"),
                            ("AP", "AP"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MG", "MG"),
                            ("MS", "MS"),
                            ("MT", "MT"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("PR", "PR"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("RS", "RS"),
                            ("SC", "SC"),
                            ("SE", "SE"),
                            ("SP", "SP"),
                            ("TO", "TO"),
                        ],
                        db_column="UF",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "status_reserva",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovada", "Aprovada"),
                            ("Concluída", "Concluída"),
                        ],
                        db_column="STATUS_RESERVA",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "nome_acomp1",
                    models.CharField(
                        blank=True, db_column="NOME_ACOMP1", max_length=100, null=True
                    ),
                ),
                (
                    "vinculo_acomp1",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Cônjuge", "Cônjuge"),
                            ("Filho até 6 anos", "Filho até 6 anos"),
                            ("Filho de 7 a 10 anos", "Filho de 7 a 10 anos"),
                            ("Filho de 11 a 23 anos", "Filho de 11 a 23 anos"),
                            ("Filho acima de 23 anos", "Filho acima de 23 anos"),
                            ("Sem vínculo familiar", "Sem vínculo familiar"),
                        ],
                        db_column="VINCULO_ACOMP1",
                        max_length=22,
                        null=True,
                    ),
                ),
                (
                    "idade_acomp1",
                    models.IntegerField(
                        blank=True, db_column="IDADE_ACOMP1", null=True
                    ),
                ),
                (
                    "sexo_acomp1",
                    models.TextField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        db_column="SEXO_ACOMP1",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "nome_acomp2",
                    models.CharField(
                        blank=True, db_column="NOME_ACOMP2", max_length=100, null=True
                    ),
                ),
                (
                    "vinculo_acomp2",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Cônjuge", "Cônjuge"),
                            ("Filho até 6 anos", "Filho até 6 anos"),
                            ("Filho de 7 a 10 anos", "Filho de 7 a 10 anos"),
                            ("Filho de 11 a 23 anos", "Filho de 11 a 23 anos"),
                            ("Filho acima de 23 anos", "Filho acima de 23 anos"),
                            ("Sem vínculo familiar", "Sem vínculo familiar"),
                        ],
                        db_column="VINCULO_ACOMP2",
                        max_length=22,
                        null=True,
                    ),
                ),
                (
                    "idade_acomp2",
                    models.IntegerField(
                        blank=True, db_column="IDADE_ACOMP2", null=True
                    ),
                ),
                (
                    "sexo_acomp2",
                    models.TextField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        db_column="SEXO_ACOMP2",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "nome_acomp3",
                    models.CharField(
                        blank=True, db_column="NOME_ACOMP3", max_length=100, null=True
                    ),
                ),
                (
                    "vinculo_acomp3",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Cônjuge", "Cônjuge"),
                            ("Filho até 6 anos", "Filho até 6 anos"),
                            ("Filho de 7 a 10 anos", "Filho de 7 a 10 anos"),
                            ("Filho de 11 a 23 anos", "Filho de 11 a 23 anos"),
                            ("Filho acima de 23 anos", "Filho acima de 23 anos"),
                            ("Sem vínculo familiar", "Sem vínculo familiar"),
                        ],
                        db_column="VINCULO_ACOMP3",
                        max_length=22,
                        null=True,
                    ),
                ),
                (
                    "idade_acomp3",
                    models.IntegerField(
                        blank=True, db_column="IDADE_ACOMP3", null=True
                    ),
                ),
                (
                    "sexo_acomp3",
                    models.TextField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        db_column="SEXO_ACOMP3",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "nome_acomp4",
                    models.CharField(
                        blank=True, db_column="NOME_ACOMP4", max_length=100, null=True
                    ),
                ),
                (
                    "vinculo_acomp4",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Cônjuge", "Cônjuge"),
                            ("Filho até 6 anos", "Filho até 6 anos"),
                            ("Filho de 7 a 10 anos", "Filho de 7 a 10 anos"),
                            ("Filho de 11 a 23 anos", "Filho de 11 a 23 anos"),
                            ("Filho acima de 23 anos", "Filho acima de 23 anos"),
                            ("Sem vínculo familiar", "Sem vínculo familiar"),
                        ],
                        db_column="VINCULO_ACOMP4",
                        max_length=22,
                        null=True,
                    ),
                ),
                (
                    "idade_acomp4",
                    models.IntegerField(
                        blank=True, db_column="IDADE_ACOMP4", null=True
                    ),
                ),
                (
                    "sexo_acomp4",
                    models.TextField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        db_column="SEXO_ACOMP4",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "nome_acomp5",
                    models.CharField(
                        blank=True, db_column="NOME_ACOMP5", max_length=100, null=True
                    ),
                ),
                (
                    "vinculo_acomp5",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Cônjuge", "Cônjuge"),
                            ("Filho até 6 anos", "Filho até 6 anos"),
                            ("Filho de 7 a 10 anos", "Filho de 7 a 10 anos"),
                            ("Filho de 11 a 23 anos", "Filho de 11 a 23 anos"),
                            ("Filho acima de 23 anos", "Filho acima de 23 anos"),
                            ("Sem vínculo familiar", "Sem vínculo familiar"),
                        ],
                        db_column="VINCULO_ACOMP5",
                        max_length=22,
                        null=True,
                    ),
                ),
                (
                    "idade_acomp5",
                    models.IntegerField(
                        blank=True, db_column="IDADE_ACOMP5", null=True
                    ),
                ),
                (
                    "sexo_acomp5",
                    models.TextField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        db_column="SEXO_ACOMP5",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "mhex",
                    models.CharField(
                        blank=True, db_column="MHEx", max_length=6, null=True
                    ),
                ),
                (
                    "uh",
                    models.CharField(
                        blank=True, db_column="UH", max_length=2, null=True
                    ),
                ),
                (
                    "valor_hosp",
                    models.DecimalField(
                        db_column="VALOR_HOSP",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_acomp1",
                    models.DecimalField(
                        db_column="VALOR_ACOMP1",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_acomp2",
                    models.DecimalField(
                        db_column="VALOR_ACOMP2",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_acomp3",
                    models.DecimalField(
                        db_column="VALOR_ACOMP3",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_acomp4",
                    models.DecimalField(
                        db_column="VALOR_ACOMP4",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_acomp5",
                    models.DecimalField(
                        db_column="VALOR_ACOMP5",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_dia",
                    models.DecimalField(
                        db_column="VALOR_DIA",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "valor_ajuste",
                    models.DecimalField(
                        db_column="VALOR_AJUSTE",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        db_column="SUBTOTAL", decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        db_column="VALOR_TOTAL",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "db_table": "base_dados",
            },
        ),
    ]
