# Generated by Django 5.0.3 on 2024-03-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedados",
            name="qtde_hosp",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                db_column="QTDE_HOSP",
                null=True,
            ),
        ),
    ]
