# Generated by Django 5.0.3 on 2024-03-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_alter_basedados_qtde_hosp"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="qtde_agua",
            field=models.IntegerField(blank=True, db_column="QTDE_AGUA", null=True),
        ),
        migrations.AddField(
            model_name="basedados",
            name="qtde_cerveja",
            field=models.IntegerField(blank=True, db_column="QTDE_CERVEJA", null=True),
        ),
        migrations.AddField(
            model_name="basedados",
            name="qtde_refri",
            field=models.IntegerField(blank=True, db_column="QTDE_REFRI", null=True),
        ),
        migrations.AddField(
            model_name="basedados",
            name="total_agua",
            field=models.DecimalField(
                db_column="TOTAL_AGUA", decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="basedados",
            name="total_cerveja",
            field=models.DecimalField(
                db_column="TOTAL_CERVEJA", decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="basedados",
            name="total_consumacao",
            field=models.DecimalField(
                db_column="TOTAL_CONSUMACAO", decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="basedados",
            name="total_refri",
            field=models.DecimalField(
                db_column="TOTAL_REFRI", decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
