# Generated by Django 5.0.3 on 2024-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_basedados_qtde_agua_basedados_qtde_cerveja_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
