# Generated by Django 5.0.3 on 2024-03-14 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_produtos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produtos",
            new_name="Produto",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="preco",
            new_name="valor",
        ),
    ]
