# Generated by Django 5.0.3 on 2024-03-14 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_rename_produtos_produto_rename_preco_produto_valor"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="produto",
            table="produto",
        ),
    ]
