# Generated by Django 5.0.3 on 2024-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_produto_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Precos_graduacao_vinculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduacao", models.CharField(max_length=100)),
                ("vinculo", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "precos_graduacao_vinculo",
            },
        ),
        migrations.CreateModel(
            name="Precos_status_graduacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("graduacao", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "precos_status_graduacao",
            },
        ),
    ]
