# Generated by Django 5.0.3 on 2024-03-14 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_precos_graduacao_vinculo_precos_status_graduacao"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="precos_graduacao_vinculo",
            table="precos_por_graduacao_e_vinculo",
        ),
        migrations.AlterModelTable(
            name="precos_status_graduacao",
            table="precos_por_status_e_graduacao",
        ),
    ]
