# Generated by Django 5.0.3 on 2024-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_alter_precos_graduacao_vinculo_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="forma_pagamento",
            field=models.CharField(
                blank=True, db_column="FORMA_PAGAMENTO", max_length=2, null=True
            ),
        ),
    ]
