# Generated by Django 5.0.3 on 2024-03-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_basedados_forma_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="cpf_pagante",
            field=models.CharField(
                blank=True, db_column="CPF_PAGANTE", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="basedados",
            name="nome_pagante",
            field=models.CharField(
                blank=True, db_column="NOME_PAGANTE", max_length=100, null=True
            ),
        ),
    ]
