# Generated by Django 5.0.3 on 2024-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_basedados_cpf_pagante_basedados_nome_pagante"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="qtde_acomp",
            field=models.IntegerField(blank=True, db_column="QTDE_ACOMP", null=True),
        ),
    ]
