# Generated by Django 5.0.3 on 2024-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_basedados_qtde_acomp"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="motivo_viagem",
            field=models.CharField(
                blank=True, db_column="MOTIVO_VIAGEM", max_length=100, null=True
            ),
        ),
    ]
