# Generated by Django 5.0.3 on 2024-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0013_alter_basedados_motivo_viagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="desc_saude",
            field=models.DecimalField(
                db_column="DESC_SAUDE", decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
