# Generated by Django 5.0.3 on 2024-03-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0014_basedados_desc_saude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedados",
            name="status_reserva",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovada", "Aprovada"),
                    ("Recusada", "Recusada"),
                    ("Concluída", "Concluída"),
                ],
                db_column="STATUS_RESERVA",
                max_length=15,
                null=True,
            ),
        ),
    ]
