# Generated by Django 5.0.3 on 2024-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0015_alter_basedados_status_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedados",
            name="motivo_viagem",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Saúde", "Saúde"),
                    ("Trabalho", "Trabalho"),
                    ("Turismo", "Turísmo"),
                ],
                db_column="MOTIVO_VIAGEM",
                max_length=20,
                null=True,
            ),
        ),
    ]
