# Generated by Django 5.0.3 on 2024-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0016_alter_basedados_motivo_viagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedados",
            name="mhex",
            field=models.CharField(
                blank=True,
                choices=[("HTM_01", "HTM_01"), ("HTM_02", "HTM_02")],
                db_column="MHEx",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="basedados",
            name="status_reserva",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovada", "Aprovada"),
                    ("Checkin", "Checkin"),
                    ("Checkout", "Checkout"),
                    ("Recusada", "Recusada"),
                    ("Pago", "Pago"),
                ],
                db_column="STATUS_RESERVA",
                max_length=15,
                null=True,
            ),
        ),
    ]
