# Generated by Django 5.0.3 on 2024-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0017_alter_basedados_mhex_alter_basedados_status_reserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedados",
            name="observacao",
            field=models.TextField(
                blank=True, db_column="OBSERVACAO", max_length=100, null=True
            ),
        ),
    ]
