# Generated by Django 5.0.3 on 2024-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0018_basedados_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedados",
            name="valor_ajuste",
            field=models.DecimalField(
                blank=True,
                db_column="VALOR_AJUSTE",
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
            ),
        ),
    ]
