# Generated by Django 5.0.3 on 2024-04-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0019_alter_basedados_valor_ajuste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedados",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CIVIL", "CIVIL"),
                    ("MILITAR DA ATIVA", "MILITAR DA ATIVA"),
                    ("MILITAR DA RESERVA", "MILITAR DA RESERVA"),
                    ("PENSIONISTA", "PENSIONISTA"),
                    ("DEP DESACOMPANHADO", "DEP DESACOMPANHADO"),
                ],
                db_column="STATUS",
                max_length=25,
                null=True,
            ),
        ),
    ]
