# Generated by Django 5.0.3 on 2024-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_basedados_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedados',
            name='qtde_pet',
            field=models.IntegerField(blank=True, db_column='QTDE_PET', null=True),
        ),
        migrations.AddField(
            model_name='basedados',
            name='total_pet',
            field=models.DecimalField(db_column='TOTAL_PET', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='basedados',
            name='uh',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], db_column='UH', max_length=2, null=True),
        ),
    ]
