# Generated by Django 5.0.3 on 2024-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_basedados_qtde_pet_basedados_total_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedados',
            name='uh',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], db_column='UH', max_length=2, null=True),
        ),
    ]
